### ISSUE TITLE
pull correct stats from bitcoinpool

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#187]
We should calculate round_shares from bitcoinpool by pulling hashrate and roundtime from bcp website as they are faking their json stats (reset them multiple times per hour).

**Comment by c00w** [comment]
OK. The api methods have been coded. I think it is re_ratedurration?

**Comment by sdogi** [comment]
Ok I started fixing this using re_rateduration but I'm kind a stumped because I don't think it can be solved with just regular expressions. Even if it can be then I don't think it is really good idea to keep the conf file like this to avoid new problems in the future.

You see this site reports duration in multiple ways:
--  01h 29m 59s

and also

04d 14h 24m 01s

So you would need conditional match {0,1} on the whole "04d&nbsp;" part from which 04 I want to match but the "d&nbsp;" part doesn't exist when the round duration has been less than a day. I think this might be possible to solve using lookahead/lookbehind and I'm trying to do it right now but yesterday I was talking with jtaylor about pools.cfg and he had this nifty idea that pools.cfg should allow Python code.

It would be really nice if there were api_method: python_exec for example which basically just uses exec() or eval() on whatever source code api_address: returned.

**Comment by sdogi** [comment]
Ok regexp line is: Round Duration: <d class=\"info\">(?:([0-9]+)d&nbsp;)?([0-9]+)h&nbsp;([0-9]+)m&nbsp;

Need to figure out this whole git thing now to apply it and see what happens when day is zero length with api_key_duration_day_hour_min

**Comment by sdogi** [comment]
Initial testing shows that api_key_duration_day_hour_min doesn't support zero length matches:

Traceback (most recent call last):
  File "<pyshell#181>", line 1, in <module>
    day = int(match.group(1).replace(' ', ''))
AttributeError: 'NoneType' object has no attribute 'replace'

Would be nice if somebody could take a look into it.. still figuring out the whole git thing. Still thinking that enabling Python full support is much better idea.

**Comment by sdogi** [comment]
I think I fixed it all, going to test and try to send the patches

**Comment by sdogi** [comment]
Send patches.. see issue #191

They banned me very shortly though probably because of fetching their main page too often or with bad user-agent.

Not sure how to approach this really. We could fix it by polling for data less often and with nice spoofed user-agent but I'm not sure if this is good idea.. maybe anyone has any better idea?

**Comment by sdogi** [comment]
Not sure where to post this but it is kind a related to bitcoinpool so I'm going to post it in here.

I think I might have been actually banned because of low efficiency:

Requested Shares:    405
Submitted Shares:    36
Efficiency:      9%

What causes this though? Is something broken that generates too many getwork requests?

So this patch might actually work very well.. but there is something else broken?

**Comment by annawaw** [comment]
On my local machine I did the following patch:

I used the stats from the main page (they seem to be updated more often than in the usef profile):
[bcpool]
api_key_ghashrate: Pool Speed: <d class="info">([.0-9]+) Gh\/s
api_key_duration_day_hour_min: Round Duration: <d class="info">(?:([0-9]+)d& nbsp;)?([0-9]+)h& nbsp;([0-9]+)m& nbsp;

In the 'api_key_duration_day_hour_min' for the get_duration I used:
day = int((output.group(1) or '0').replace(' ', ''))

**Comment by sdogi** [comment]
My patch has been applied to latest already and people report that it is working. I got banned however but probably because of bad efficiency

**Comment by Endeavour79** [comment]
works. done.

thank you!
