### ISSUE TITLE
Some error I got just now

### ISSUE THREAD

**Issue by simonk83** [c00w/bitHopper#194]
Using latest Gnaget version:

http://pastebin.com/kMTiJQ9Q

**Comment by sdogi** [comment]
At first I thought that the culprit seems to be irclib.py-s function process_once.

irclib.py line 212:
        if sockets:
            (i, o, e) = select.select(sockets, [], [], timeout)
            self.process_data(i)

I tested it and I don't know how he managed to generate so many sockets with it though. Was going to fix it by making it check if there are >= 512 descriptors being feeded to select.select() through sockets array. If that's the case break the array up so that it could handle it properly.

However I think that the bug might actually be in Bithopper itself somewhere since it also uses twisted. Unfortunately I'm unfamiliar with twisted and can't see through the abstraction to find where the bug happens. I guess the fix should be done the same way as with irclib.py but on Bithopper not twisted level of course.

**Comment by c00w** [comment]
This bug was appearing a while ago and I killed it by updating code to not use as many bloody sockets. I'll see if I can track it down.

**Comment by c00w** [comment]
Um, I may have fixed it. I'm closing the issue. If it reappears reopen please.
