### ISSUE TITLE
v0.2.1 - connection issue still

### ISSUE THREAD

**Issue by Clipseza** [c00w/bitHopper#226]
Well I hoped it fixed it changing 1 to 4 connections however after about 4hours of running the connections seem to have died and same problem occured as with connections set to 1 in version 0.2.0

Will keep checking to but right now I think the only solution is for me to update to latest but keep using the old connection code from before version 2.0.0

**Comment by sdogi** [comment]
This seems perfect on Windows right now with about ~40 connections. Since there are about 34 pools in the list with mine/disable and I have 2 workers connected it is exactly how it is supposed to be. However it seems Clipse is reporting problems on *nix.

I see he already made a ticket in here but a small log about this behavior wouldn't hurt:

15:55 <+Clipse> yes no more miner connections
15:55 <+Clipse> reload hopper
15:55 <+Clipse> they connect
15:55 <+Clipse> then slowly drop
15:56 <+Clipse> and never reconnect

Seems like old connections are left open and they choke bithopper on new worker connections.

Ok I have been looking around. I'm curious why you are using your own added twisted client.py instead of twisted.web.client from import?

I did a diff on my client.py with twisted 11 and the one included with bithopper and it seems your client.py adds persistent connections. Since this isn't in latest twisted though then this tells me it is experimental?

Couldn't getworks be resolved with something like Eventlet or Gevent.. or that would require lots of rewriting and coding additional features?

When we would go over to Eventlet we would never have issues with bithopper not being able to handle connections. On a decent server daemon that uses eventlet can easily handle 1000 requests/second.

I know lot of people have gone over to these because twisted is also maintenance hell.

**Comment by c00w** [comment]
I'll add a switch to use the older connection code and increase the maximum connections to 10.

**Comment by c00w** [comment]
I'd love to switch out of python but haven't found anything better.

**Comment by c00w** [comment]
And I added a --OldConnectionSystem flag. And I upped the connection limits as well.

**Comment by c00w** [comment]
But now I want to port all of this code to use eventlet...

**Comment by sdogi** [comment]
No point of switching out of Python, it's the best.

eventlet or gevent would make life much easier for this project though than with tyrannosaurus called twisted so I'm all for porting it to eventlet!

**Comment by c00w** [comment]
The one issue with the porting is that most of this code is not threadsafe at all. Making the smaller modules thread safe should be quick. Making the bigger modules threadsafe may be a disaster.

**Comment by c00w** [comment]
But what the heck. I'm working on making the modules threadsafe then we will swap over to eventlet.

**Comment by c00w** [comment]
We switched to eventlet. Closing this issue.
