### ISSUE TITLE
Milliseconds in console timestamp by zilch80

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#306]
Would be a very apreciated feature for better adjusting LP penalty

**Comment by c00w** [comment]
Um. The debug log now prints the exact time recieved.

**Comment by paraipan** [comment]
from what he explained on irc he would want %H:%M:%S.%milliseconds in console to be more precise than seconds. dunno if it's possible to implement that easy from what i found about python

**Comment by c00w** [comment]
Um. The issues is that there is a limited per second resolution at the default level. We could get more accurate information but it takes more libraries. And we are scoring based on the time given in the EXACT TIME debugging messages.

**Comment by paraipan** [comment]
ah ok got it

**Comment by zilch80** [comment]
Few crossed wires, :). Was just saying I'd changed bithopper.py to put 100ths of a sec on the time stamp, but after asking c00w if the stamps reported to the standard log the are same as the times used for LP detection of blocks he said no, then exposed the exact times used in the debug output, which is whats useful for tuning LP penalties.

For what its worth:
- str(Decimal(str(time.time())) % 1)[2:] +

is what I added to each of the print lines in the log_msg method in bitHopper.py to get 100ths.

And this because I'm playing with parsing the log output to provide accuracy as well as LP tweaks and need days of data:

print time.strftime("[%d:%m:%H:%M:%S:") + str(Decimal(str(time.time())) % 1)[2:] + "] " + str(msg)

thats the whole line for day and month, as well as formatted to include 100ths in the braces.

Again, thanks for the extact time debug output!

**Comment by c00w** [comment]
Okay. I'm closing this issue.
