### ISSUE TITLE
Feature: Sum of total recieved and expected.

### ISSUE THREAD

**Issue by organofcorti** [c00w/bitHopper#347]
Could we get a sum total of received/expected so we can get total efficiency?

Cheers

ooc

**Comment by c00w** [comment]
Sure. Its on the backend. I'll see about adding it to the front end.

**Comment by sdogi** [comment]
I require this too so I'll take this

**Comment by sdogi** [comment]
Done:
https://github.com/c00w/bitHopper/pull/468

c00w I couldn't find it from backend though but I solved it using javascript which should actually be even more lightweight since totals get calculated on the client side even though it shouldn't really matter.

I guess eventually this should be rewritten to use backend though for optimization but right now it is very fast and works well.

**Comment by sdogi** [comment]
This can be closed now

**Comment by organofcorti** [comment]
Thanks sdogi!
