### ISSUE TITLE
BUG: Strage error and behavior (reopened) 

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#457]
Seems this issue it's not fixed entirely

https://github.com/c00w/bitHopper/issues/448

**Comment by itstooez** [comment]
Reposted:

http://pastebin.com/8ygKUDqu

It's still not fixed.  LP went to deepbit, then re-assigned to Ars after their stats went to 0...shortly after, a share was submitted to Ars.  Ars is on backup.

What happens in lines 85-90, should be similar to what we are trying to do here I think...

**Comment by c00w** [comment]
Thats what should happen. We're sending back a LP with a workunit when we change the server owner. So arsbitcoin becomes the new server owner and we aren't mining deepbit anymore. A couple shares come in from previous deepbit work and get routed there then ars work starts coming back and we send it to ars.

Why shouldn't we have set shares to arsbitcoin?

**Comment by paraipan** [comment]
dunno if it's related c00w, i'm getting more rejects than usual with latest. aprox. 4-5%

**Comment by itstooez** [comment]
Ars is set to the backup role.  If the block gets reassigned as theirs via API stats, after it was assigned to deepbit via mine_lp...it shouldn't send getworks from a backup pool I would think.

The entire goal of this request was to imitate the actions of deepbit when it receives an LP...pass the LP over to the miner so that they flush out old work and gather new work; because of the block being reassigned via API stats.  Line 85-90 seem to accomplish this, as that's what's called for the deepbit side when on mine_lp.

The same things that happen to deepbit when on mine_lp should be happening to whatever pool gets reassigned the block. (http://pastebin.com/yq7rzeCH)

Sorry if I'm not being very clear on this.

**Comment by c00w** [comment]
It is happening. Another LP is triggered, we send the miners a new work unit via the LP channel and bitHopper starts serving work from the new server.

Ideally the miners would also flush their work queues. However most miners are "Smart" enough to not do that when the block doesn't change. Which is why there is no getwork "spam"

**Comment by itstooez** [comment]
Ah gotcha, so I guess it's an "issue" with the miner at this point.  Flushing the work queue would be what's desired here, but I guess there's no way to force that, unless it's a new block.

So there's still the potential of the miner working on the deepbit work.  So I wonder then if this really has any added benefit, my ideal goal was to have it clear the work queue :/

**Comment by c00w** [comment]
Um it has a little bit of benefit because at least one work from the new server gets added to the queue and it may cause some miners to flush.

If you really want to make this behavior more common tell the miner to only queue 1 work and this should flush their queue.

**Comment by itstooez** [comment]
Very well, thank you !

**Comment by paraipan** [comment]
closing issue...

**Comment by paraipan** [comment]
man this is getting tricky, could we check if a pool has a mine related role before we actually start to work with them ?  i'm submitting shares to slush and have it on "info", all rejects by the way

**Comment by c00w** [comment]
It should be checked already.... Why are you submitting shares to slush?

Are you on the latest build?

**Comment by paraipan** [comment]
dunno, last ver. is submitting shares to every pool that finds a block (api resets) with "info" role, a few shares only and they become stale shares. In the morning almost every "info" pool is lagged (red) because bH doesn't have account info on those pools.

**Comment by paraipan** [comment]
issue has been fixed :)
