### ISSUE TITLE
BUG: Upstream crash, (error log)

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#508]
http://pastebin.com/YKtz2mE6

**Comment by c00w** [comment]
What OS and miner are you using?

**Comment by c00w** [comment]
Also are you on the latest version?

**Comment by Transisto** [comment]
win7 python 2.7, always on latest, 

I have double checked the user.conf and found a pool without a role:

I had previously replaced all : mine:info with  mine : disable
It freed a lot of connection on the router

**Comment by c00w** [comment]
Hmmm. It looks like the remote host hung up which is a bug with the WSGI server that it is throwing exceptions. Not anything we can do about it.

**Comment by Transisto** [comment]
what "remote host"? 
Do you suggest me installing BH on a new OS , reinstalling python, or test deleting all pool but one ?

**Comment by c00w** [comment]
None of them will help. Your miner is closing connections in a wierd way. I'll take a look to see if I can find a better polling method for windows.

**Comment by Transisto** [comment]
Seems like you're suggesting installing over linux would fix the problem.

I'm using BAMT  (phatk2) @ ~20Ghs

**Comment by c00w** [comment]
EDIT: Yes switching to linux will solve the problem

Um, It wouldn't fix the problem. If your miner is closing connections improperly the errors are thrown. They don't effect anything. The too many file descriptors in select is because eventlet is using select on windows. If I could find a better polling library for windows I would tell you to install it. For linux we use libevent. However if your miner is thrashing connections badly enough to overflow the socket select then It'll probably not crash on linux but will still cause wierd behavior.

The following will help you in order of priority:
1) Use a miner which use http1.1 and doesn't close remote connections very rapidly Ex Poclbm
2) Disable all of your info pools to help save on sockets.
3) Wait for me to research polling libraries on windows and find a better one that eventlet can utilize.
4) Use linux.

**Comment by c00w** [comment]
Okay, so Libevent is available for windows. http://sourceforge.net/projects/levent/
However windows has no equivalent method besides select so we run into the same issues.
Switching to linux is your best bet.
