### ISSUE TITLE
Bug: nmcbit.com duration calculation bad

### ISSUE THREAD

**Issue by amrando** [c00w/bitHopper#539]
The current pools.cfg uses duration for nmcbit.  Currently, my BH is mining on nmcbit (btc prop).  Current stats are:
BTC Current round started at:   Dec 27th, 08:33:51 am
BTC Current round duration: 29:37:00 hours
Valid shares for current round: 1,004,346
Shares for current round:   1,011,258

15.23 Ghash/s from 52 workers

BH should not be mining on nmcbit prop/btc at this point.

In a previous version BH used the shares.  The nmcbit stats page still shows shares.  Can we change it back?  There doesn't seem to be a need to use duration.

I am using the latest version pulled just a few minutes ago

**Comment by Locky7** [comment]
This has been a ongoing problem.  First, your right on it working once upon a time, then it broke.  I put in the original issue to fix it.  Turns out it is difficult, which lead to me trying to figure the pools.cfg and how to modify it to work for new pools and hopefully fix nmcbit.com.  So, all the work I have contributed started by the quest to hop nmcbit for BTC.  What you have is the best I could do, cause they way the stats are presented in html, nmc round shares come first on the page and BH pulls those and not BTC.  

The solution I used is a work around to approximate the share count by using the round time and pool's current hash rate to determine what the round shares should be, which is "api_method: re_rateduration."  It works good until you restart BH and it tries to determine the round shared with a lower current hash rate, thus you get a lower share count than if you accounted for the big spike at the start.  That history is lost by  restarting in mid  to late in the round.  

Since the NMC/BTC round shares are presented in a table and the two round shares are not distinguishable, BTC round shares must be approximated. Resetting to 100% like with mine_lp on "api_method: re_rate" is probably a better solution after restart or  write an api for nmcbit to skip the first instance of round shares and use the second.  

For now Amazing, I use the penalty ranging from  2-4 to stop BH from mining at NMCbit.com for BTC after a restart.  It's risky, cause you will hop out too early if you don't change it after a new round.  A better solution is indeed needed.

**Comment by c00w** [comment]
Um, I can fix this. We can do something like [0-9]+ <blah tags etc...> ([0-9]+) to pull the second item. Or you can just match on ([0-9]+) and use a different group. I'm trying to clean up the core a little bit but when I have time I'll fix it.

**Comment by amrando** [comment]
I helped do the first scrape a couple months ago. I seemed to work. Don't know what happened where it needed to change and duration was the solution. But it would be much better if we can get shares directly.

Thanks for your work on BH. by mid-January I'll be up to 40gh/s, all running through BH. It's good to know my donation is being put to good use! :)

**Comment by Locky7** [comment]
I think the page was changed.  However, your setup is sure something!

**Comment by Locky7** [comment]
submitted pull request with an ugly fix.

**Comment by amrando** [comment]
Thank you!

Hopefully we can find a longer term solution too.

**Comment by c00w** [comment]
I'm closing this issue as this part of the codebase has been rewritten.
