### ISSUE TITLE
TCP connection timed out: 10060

### ISSUE THREAD

**Issue by RyanSingley** [c00w/bitHopper#6]
I keep getting the following error when it's working on bitclockers.  It then switches to my default server, for a short while and then switches back to bitclockers.

TCP connection timed out: 10060: A connection attempt failed because the connect
ed party did not properly respond after a period of time, or established connect
ion failed because connected host has failed to respond..

**Comment by c00w** [comment]
Hmmm. It looks like bitclockers is probably dropping connections from you. Maybe you have bad latency. Who knows. The behavior you describe is normal for when a server stops working. It switches to the next best pool which may be the backup pool.

If you don't want to use bitclockers for pool hopping run with --disable bitclockers.

Otherwise that is nothing to worry about.

**Comment by c00w** [comment]
If you want me to take a deeper look attach the log and I'll see if anything is wrong on my end.

**Comment by RyanSingley** [comment]
Thanks for the response.  I think I'll just disable it.  Thanks for the
script!

**Comment by c00w** [comment]
Okay. I'm closing the issue for now.
