### ISSUE TITLE
"Install gitpython! See the readme for detailed instructions", but it is installed

### ISSUE THREAD

**Issue by lunks** [c00w/bitHopper#600]
```
root@bp:/opt/bitHopper# pip search gitpython
GitPython                 - Python Git Library
  INSTALLED: 0.3.2.RC1 (latest)
kr-GitPython              - Python Git Library
root@bp:/opt/bitHopper# python bitHopper.py 
Install gitpython! See the readme for detailed instructions
Exception KeyError: KeyError(140592844511696,) in <module 'threading' from '/usr/lib/python2.6/threading.pyc'> ignored
```

**Comment by c00w** [comment]
Which version are you using? I just updated a bunch of stuff a couple of hours ago which made the gitpython system much more robust.

**Comment by c00w** [comment]
Also how did you download bitHopper? git checkout? Zip? Svn? I'm just trying to get reproduction steps so I can test and fix it myself.

**Comment by vcaxx** [comment]
I have the same problem in Ubuntu and Debian.
I tried both installing gitpython through pip and from the link in README.
I did git checkout of the newest version just now. I confirm that the problem is still here, slightly different keyError for Python 2.7.2:

root@(none):~/install/newHopper/bitHopper# ./run-bithopper.sh 
Install gitpython! See the readme for detailed instructions
Exception KeyError: KeyError(3076330164L,) in <module 'threading' from '/usr/local/lib/python2.7/threading.pyc'> ignored

**Comment by vcaxx** [comment]
It seems that I have been missing httplib2 python module. 
So, "pip install httplib2" solved it for me.

Should this be included in README?

**Comment by lunks** [comment]
Thanks @vcaxx, I installed httlib2 and importlib. It worked after that.

This should probably be included in the README. If you're not doing the pull request, let me know and I'll do it.

Thanks!

**Comment by c00w** [comment]
Did installing httplib2 fix things? I can add it to the readme but I bundled it with bitHopper.

**Comment by c00w** [comment]
Oh and importlib is only needed on 2.6.

**Comment by lunks** [comment]
Installing both fixed everything, @c00w.
