### ISSUE TITLE
ImportError: No module named gevent.hub

### ISSUE THREAD

**Issue by keshavreddy** [c00w/bitHopper#703]
I am trying to run openerp application through gevent  but throwing below error, I've 
gevent.1.0 and latest greenlet but I am unable to resolve it please help me

C:\openerp\server\server>openerp-server --gevent C:\Python26\Lib\site-packages\g
event-1.0-py2.6-win32.egg
Traceback (most recent call last):
  File "C:\python26\lib\site-packages\py2exe\boot_common.py", line 92, in <modul
e>
  File "linecache.pyc", line 9, in <module>
    i    Nt
  File "C:\openerp\server\server.\os.py", line 11, in <module>
    from gevent.hub import get_hub, reinit
ImportError: No module named gevent.hub
Traceback (most recent call last):
  File "openerp-server", line 2, in <module>
  File "C:\openerp\server\server.\openerp__init__.py", line 30, in <module>
    import os
  File "C:\openerp\server\server.\os.py", line 11, in <module>
    from gevent.hub import get_hub, reinit
ImportError: No module named gevent.hub

**Comment by c00w** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

This is probably the wrong issue tracker, since you're talking about
openerp and this is the issue tracker for bitHopper.

On 06/02/2014 02:29 AM, keshavreddy wrote:

> I am trying to run openerp application through gevent but throwing
> below error, I've gevent.1.0 and latest greenlet but I am unable to
> resolve it please help me
> 
> C:\openerp\server\server>openerp-server --gevent 
> C:\Python26\Lib\site-packages\g event-1.0-py2.6-win32.egg Traceback
> (most recent call last): File
> "C:\python26\lib\site-packages\py2exe\boot_common.py", line 92, in
> e> File "linecache.pyc", line 9, in i    Nt File
> "C:\openerp\server\server.\os.py", line 11, in from gevent.hub
> import get_hub, reinit ImportError: No module named gevent.hub 
> Traceback (most recent call last): File "openerp-server", line 2,
> in File "C:\openerp\server\server.\openerp__init__.py", line 30,
> in import os File "C:\openerp\server\server.\os.py", line 11, in 
> from gevent.hub import get_hub, reinit ImportError: No module named
> gevent.hub
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/c00w/bitHopper/issues/703.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQEcBAEBAgAGBQJTjCCoAAoJEHP1nN3uZoHuCRMIALuz13FTHkIYSXT0Pu7x1aQK
z2dOd5NlRhz9pm3JzunkIpFT+mhryFT1A33mOrY+qZKl+vm8g4XQcva0H+5SjZ9H
rO5/mTuTIsEiBqXfvRAIMMdPT115OJLD7LGBCc49fFsZB4n2xXeXerMSv5o5ozjq
5IBEJubNXW0QHFaFj3mhrQvh7y1gbYRmCmYbtKkFci2NX84bT8f3GEwE4m2WNhL1
mM0WS31W7GGMnlaQWwSd5kR5rdsWVTZHBR6o7Y0tlJDeyNr+BJcvzAAjiQ/JBeIf
WrWQBZKg03Ns1Ln5wnWyvKRdF6RNqQYdHhM6gBLsoVUkOhSmq2mSUxMcswniER0=
=zoVK
-----END PGP SIGNATURE-----
